apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ca9tw7l5q-java-quarkus
  janus-idp.io/tekton: ca9tw7l5q-java-quarkus
  backstage.io/kubernetes-id: ca9tw7l5q-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ca9tw7l5q-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
