apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ca9tw7l5q-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-f0fa20cb3a.xlwz.p3.openshiftapps.com/rhtap/rhtap-qe:5e5e6f991058e8cc9978950cd09ba4f7c1ce32f9@sha256:ae449c50e95bd721b4e769806efcc8ff54c086380fd2f57de2150e3baf5df246
          name: container-image
